//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowMUD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShadowMUD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid salt length..
        /// </summary>
        internal static string BCryptInvalidSaltLengthString {
            get {
                return ResourceManager.GetString("BCryptInvalidSaltLengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming name for new character.
        /// </summary>
        internal static string ConfirmNameString {
            get {
                return ResourceManager.GetString("ConfirmNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming password for new character.
        /// </summary>
        internal static string ConfirmPasswordString {
            get {
                return ResourceManager.GetString("ConfirmPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Accepted: {0}({1}).
        /// </summary>
        internal static string ConnectionAcceptedString {
            get {
                return ResourceManager.GetString("ConnectionAcceptedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Closed: {0}({1}).
        /// </summary>
        internal static string ConnectionClosedString {
            get {
                return ResourceManager.GetString("ConnectionClosedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting password for existing character.
        /// </summary>
        internal static string GetExistingPasswordString {
            get {
                return ResourceManager.GetString("GetExistingPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting password for new character.
        /// </summary>
        internal static string GetPasswordString {
            get {
                return ResourceManager.GetString("GetPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains one or more invalid characters, requesting new name..
        /// </summary>
        internal static string InvalidNameString {
            get {
                return ResourceManager.GetString("InvalidNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening on 192.168.0.2:4003.
        /// </summary>
        internal static string ListenString {
            get {
                return ResourceManager.GetString("ListenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Entered: {0}.
        /// </summary>
        internal static string NameEnteredString {
            get {
                return ResourceManager.GetString("NameEnteredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains more than 12 characters, requesting new name..
        /// </summary>
        internal static string NameTooLongString {
            get {
                return ResourceManager.GetString("NameTooLongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains fewer than 2 characters, requesting new name..
        /// </summary>
        internal static string NameTooShortString {
            get {
                return ResourceManager.GetString("NameTooShortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains no vowels, requesting new name..
        /// </summary>
        internal static string NoVowelsInNameString {
            get {
                return ResourceManager.GetString("NoVowelsInNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player exists, loaded character information..
        /// </summary>
        internal static string PlayerExistsString {
            get {
                return ResourceManager.GetString("PlayerExistsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player DOES NOT exist, creating new character information..
        /// </summary>
        internal static string PlayerNotExistString {
            get {
                return ResourceManager.GetString("PlayerNotExistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing state reached..
        /// </summary>
        internal static string PlayingStateReachedString {
            get {
                return ResourceManager.GetString("PlayingStateReachedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying gender for new character.
        /// </summary>
        internal static string QueryGenderString {
            get {
                return ResourceManager.GetString("QueryGenderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocketException: {0}.
        /// </summary>
        internal static string SocketExceptionString {
            get {
                return ResourceManager.GetString("SocketExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name appears to be valid, continuing..
        /// </summary>
        internal static string ValidNameString {
            get {
                return ResourceManager.GetString("ValidNameString", resourceCulture);
            }
        }
    }
}
